# fly.toml app configuration file generated for red-surf-4563 on 2023-08-01T16:08:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-surf-4563"
primary_region = "ams"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
